os: linux
dist: xenial
language: python
python:
- 3.7.9
install:
- pip install flask
addons:
  sonarcloud:
    organization: joaonart
    token: ${SONAR_TOKEN}
# Defini o script de Teste que deve rodar toda vez que o c√≥digo for alterado.
script:
  - python -m unittest -v test || travis_terminate 1;
  - sonar-scanner || travis_terminate 1;
deploy:
- provider: heroku
  api_key: "$HEROKU_API_KEY"
  edge: true
  app: devopslab-joaonart
  on:
    branch: master
- provider: gae
  keyfile: "../../../devopslab-320323-1b8c1ebd8850.json"
  project: devopslab-320323
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_13ecc076868e_key -iv $encrypted_13ecc076868e_iv -in devopslab-320323-1b8c1ebd8850.json.enc -out ~/devopslab-320323-1b8c1ebd8850.json -d
